// generated by stringer -type=FieldID; DO NOT EDIT

package apachelogs

import "fmt"

const _FieldID_name = "FIELD_IPFIELD_USER_IDFIELD_DATE_TIMEFIELD_METHODFIELD_URIFIELD_QUERY_STRINGFIELD_PROTOCOLFIELD_STATUSFIELD_SIZEFIELD_REFERRERFIELD_USER_AGENTFIELD_PROC_TIMEFIELD_DATEFIELD_TIME"

var _FieldID_index = [...]uint8{0, 8, 21, 36, 48, 57, 75, 89, 101, 111, 125, 141, 156, 166, 176}

func (i FieldID) String() string {
	i -= 1
	if i >= FieldID(len(_FieldID_index)-1) {
		return fmt.Sprintf("FieldID(%d)", i+1)
	}
	return _FieldID_name[_FieldID_index[i]:_FieldID_index[i+1]]
}
