// generated by stringer -type=OperatorID; DO NOT EDIT

package apachelogs

import "fmt"

const _OperatorID_name = "OP_LESS_THANOP_GREATER_THANOP_EQUAL_TOOP_NOT_EQUALOP_REGEX_EQOP_REGEX_NEOP_CONTAINSOP_NOT_CONTAIN"

var _OperatorID_index = [...]uint8{0, 12, 27, 38, 50, 61, 72, 83, 97}

func (i OperatorID) String() string {
	i -= 1
	if i >= OperatorID(len(_OperatorID_index)-1) {
		return fmt.Sprintf("OperatorID(%d)", i+1)
	}
	return _OperatorID_name[_OperatorID_index[i]:_OperatorID_index[i+1]]
}
